"""added foreign keys owner to urls

Revision ID: 416279f92abc
Revises: a6e2478028f2
Create Date: 2026-04-11 11:06:48.951237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416279f92abc'
down_revision: Union[str, Sequence[str], None] = 'a6e2478028f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URLS', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('URLS', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key("urls_user_fk", 'URLS', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("urls_user_fk", 'URLS', type_='foreignkey')
    op.drop_column('URLS', 'created_at')
    op.drop_column('URLS', 'owner_id')
    # ### end Alembic commands ###
