"""create URL table

Revision ID: 8b6146d77515
Revises: 
Create Date: 2026-04-09 14:55:01.113078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6146d77515'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URLS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_URL', sa.String(), nullable=False),
    sa.Column('short_URL', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URLS')
    # ### end Alembic commands ###
